export interface LessonMeta {
  title: string;
  part: string;
  partId: string;
  lessonNumber: string;
  slug: string;
  prerequisite: string | null;
  isFree: boolean;
  summary: string;
  readTime: number;
}

export interface CoursePart {
  id: string;
  label: string;
}

export const COURSE_PARTS: CoursePart[] = [
  { id: "part-0", label: "Part 0 — The On-Ramp" },
  { id: "part-1", label: "Part 1 — JavaScript for Playwright" },
];

export const PLAYWRIGHT_LESSONS: LessonMeta[] = [
  // ── Part 0 ──────────────────────────────────────────────────────────────
  {
    title: "What is software testing?",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.1",
    slug: "what-is-software-testing",
    prerequisite: null,
    isFree: true,
    summary: "Told through a real bug that cost a company $440 million in 45 minutes.",
    readTime: 6,
  },
  {
    title: "Manual vs automated testing",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.2",
    slug: "manual-vs-automated-testing",
    prerequisite: "what-is-software-testing",
    isFree: true,
    summary: "Why automation is a career, not just a skill.",
    readTime: 5,
  },
  {
    title: "What a website is made of",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.3",
    slug: "what-a-website-is-made-of",
    prerequisite: "manual-vs-automated-testing",
    isFree: true,
    summary: "You click a button — what actually happens behind the scenes?",
    readTime: 7,
  },
  {
    title: "Install everything",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.4",
    slug: "install-everything",
    prerequisite: "what-a-website-is-made-of",
    isFree: true,
    summary: "Node.js, VS Code, and your first project folder — hand-held for Windows and macOS.",
    readTime: 15,
  },
  {
    title: "The terminal, demystified",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.5",
    slug: "the-terminal-demystified",
    prerequisite: "install-everything",
    isFree: true,
    summary: "Typing commands instead of clicking — less scary than it looks.",
    readTime: 8,
  },
  {
    title: "Your roadmap",
    part: "Part 0 — The On-Ramp",
    partId: "part-0",
    lessonNumber: "0.6",
    slug: "your-roadmap",
    prerequisite: "the-terminal-demystified",
    isFree: true,
    summary: "You'll write your first automation by Lesson 1.18. Here's exactly how we get there.",
    readTime: 4,
  },
  // ── Part 1 ──────────────────────────────────────────────────────────────
  {
    title: "What is JavaScript?",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.1",
    slug: "what-is-javascript",
    prerequisite: "your-roadmap",
    isFree: true,
    summary: "What JavaScript is, where it runs, and what Node.js has to do with it.",
    readTime: 5,
  },
  {
    title: "Running a .js file",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.2",
    slug: "running-a-js-file",
    prerequisite: "what-is-javascript",
    isFree: true,
    summary: "Write your first line of code, run it, and see output in the terminal.",
    readTime: 6,
  },
  {
    title: "let and const",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.3",
    slug: "let-and-const",
    prerequisite: "running-a-js-file",
    isFree: true,
    summary: "Storing information with the right keyword — and why we skip var.",
    readTime: 6,
  },
  {
    title: "Data types",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.4",
    slug: "data-types",
    prerequisite: "let-and-const",
    isFree: true,
    summary: "string, number, boolean, null, undefined — the five flavours of data.",
    readTime: 7,
  },
  {
    title: "Template literals",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.5",
    slug: "template-literals",
    prerequisite: "data-types",
    isFree: true,
    summary: "Mixing text and variables with backticks — cleaner than + concatenation.",
    readTime: 5,
  },
  {
    title: "Comparison operators",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.6",
    slug: "comparison-operators",
    prerequisite: "template-literals",
    isFree: true,
    summary: "=== and !== — asking JavaScript a yes/no question.",
    readTime: 5,
  },
  {
    title: "Logical operators",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.7",
    slug: "logical-operators",
    prerequisite: "comparison-operators",
    isFree: true,
    summary: "&& || ?? and ?. — combining conditions and handling missing values.",
    readTime: 7,
  },
  {
    title: "if / else and ternary",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.8",
    slug: "if-else-and-ternary",
    prerequisite: "logical-operators",
    isFree: true,
    summary: "Making decisions in code — if/else and the shortcut ? : form.",
    readTime: 6,
  },
  {
    title: "for and for...of",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.9",
    slug: "for-loops",
    prerequisite: "if-else-and-ternary",
    isFree: true,
    summary: "Looping over many items without repeating yourself.",
    readTime: 6,
  },
  {
    title: "Function declarations vs expressions",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.10",
    slug: "function-declarations",
    prerequisite: "for-loops",
    isFree: true,
    summary: "Packaging reusable steps into a named block of code.",
    readTime: 6,
  },
  {
    title: "Arrow functions",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.11",
    slug: "arrow-functions",
    prerequisite: "function-declarations",
    isFree: true,
    summary: "The () => {} shorthand you'll see everywhere in Playwright tests.",
    readTime: 5,
  },
  {
    title: "Parameters, defaults, and return",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.12",
    slug: "parameters-and-return",
    prerequisite: "arrow-functions",
    isFree: true,
    summary: "How functions receive data, use fallbacks, and send results back.",
    readTime: 6,
  },
  {
    title: "Why the web is asynchronous",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.13",
    slug: "why-the-web-is-asynchronous",
    prerequisite: "parameters-and-return",
    isFree: true,
    summary: "The plain-English story of why JavaScript can't just wait — no code yet.",
    readTime: 5,
  },
  {
    title: "Promises",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.14",
    slug: "promises",
    prerequisite: "why-the-web-is-asynchronous",
    isFree: true,
    summary: "The ticket system JavaScript uses to handle 'I'll have that ready soon.'",
    readTime: 7,
  },
  {
    title: "async / await",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.15",
    slug: "async-await",
    prerequisite: "promises",
    isFree: true,
    summary: "The most important concept for Playwright — waiting without the pain.",
    readTime: 7,
  },
  {
    title: "try / catch",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.16",
    slug: "try-catch",
    prerequisite: "async-await",
    isFree: true,
    summary: "Catching errors before they crash your test — and deciding what to do.",
    readTime: 6,
  },
  {
    title: "Object destructuring",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.17",
    slug: "object-destructuring",
    prerequisite: "try-catch",
    isFree: true,
    summary: "The ({ page }) pattern you'll see in every Playwright test — explained.",
    readTime: 6,
  },
  {
    title: "Mini Playwright Win ★",
    part: "Part 1 — JavaScript for Playwright",
    partId: "part-1",
    lessonNumber: "1.18",
    slug: "mini-playwright-win",
    prerequisite: "object-destructuring",
    isFree: true,
    summary: "Automate a real Google search in ~10 lines. Your first working automation.",
    readTime: 15,
  },
];
